# Aponta direto para a biblioteca do pytorch lightning
_target_: pytorch_lightning.Trainer
max_epochs: 1
accelerator: auto
devices: 1
log_every_n_steps: 10 # argumento extra que vai funcionar por causa do extra="allow"
enable_checkpointing: true