defaults:
  - base_config
  - _self_ # usa as configs desse arquivo
  - /train/task@task: classification # carrega o arquivo configs/train/task/classification.yaml
  - /train/trainer@trainer: default # carrega o arquivo trainer/default.yaml
  - /data@data: fashion_mnist # carrega o arquivo fashion_mnist.yaml

project_name: "FashionMNIST_Project"
version: "2.0.0"
debug: true